### ISSUE TITLE
invalid merges

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kube-workflow#59]
when defining multiple components, values are merged incorrectly

values.yaml :
```
app-www:
  enabled: true

app-api:
  enabled: true
```

prod/values.yaml :
```
app-www:
  ingress:
    annotations:
      pouet: "42"
```

For some reason, `app-api` gets `app-www` annotations in prod
